import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

const common = {
  bundle: true,
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
};

// Two outputs from the same source so the plugin and the standalone prototype
// can never drift: main.js (Obsidian cjs) and prototype.js (browser iife).
const builds = [
  {
    ...common,
    entryPoints: ["src/main.ts"],
    outfile: "main.js",
    format: "cjs",
    external: [...builtins, "obsidian"],
    banner: { js: banner },
  },
  {
    ...common,
    entryPoints: ["src/prototype.ts"],
    outfile: "prototype.js",
    format: "iife",
    external: [],
    banner: { js: banner },
  },
];

Promise.all(builds.map((b) => esbuild.build(b)))
  .then(() => console.log("Bloom build complete: main.js + prototype.js"))
  .catch(() => process.exit(1));
