/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  BloomView: () => BloomView,
  VIEW_TYPE_BLOOM: () => VIEW_TYPE_BLOOM,
  default: () => BloomPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/dashboard.ts
var ICONS = {
  home: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 11l9-8 9 8"/><path d="M5 10v9a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-9"/></svg>`,
  today: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="8.5"/><circle cx="12" cy="12" r="2.6" fill="currentColor" stroke="none"/></svg>`,
  tasks: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1.6"/><path d="M13 4.5h8M13 8.5h6"/><rect x="3" y="14" width="7" height="7" rx="1.6"/><path d="M13 15.5h8M13 19.5h6"/></svg>`,
  calendar: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="17" rx="2"/><path d="M3 9h18M8 2v4M16 2v4"/></svg>`,
  trackers: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3v18h18"/><path d="M7 14l3-4 3 3 5-7"/></svg>`,
  learning: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 6c-2-1.4-5-1.4-7 0v11c2-1.4 5-1.4 7 0 2-1.4 5-1.4 7 0V6c-2-1.4-5-1.4-7 0z"/><path d="M12 6v11"/></svg>`,
  books: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M4 5h7v13H4zM13 5h7v13h-7z"/></svg>`,
  projects: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7a2 2 0 0 1 2-2h3l2 2h9a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>`,
  search: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/></svg>`,
  settings: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9 2 2 0 1 1-2.8 2.8 1.7 1.7 0 0 0-2.9 1.2 2 2 0 1 1-4 0 1.7 1.7 0 0 0-2.9-1.2 2 2 0 1 1-2.8-2.8 1.7 1.7 0 0 0-1.2-2.9 2 2 0 1 1 0-4 1.7 1.7 0 0 0 1.2-2.9 2 2 0 1 1 2.8-2.8 1.7 1.7 0 0 0 1.9-.3 1.7 1.7 0 0 0 1.2-2.9 2 2 0 1 1 4 0 1.7 1.7 0 0 0 2.9 1.2 2 2 0 1 1 2.8 2.8 1.7 1.7 0 0 0-.3 1.9z"/></svg>`,
  sun: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>`,
  moon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg>`,
  chevL: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 6l-6 6 6 6"/></svg>`,
  chevR: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 6l6 6-6 6"/></svg>`
};
var NAV = [
  { id: "home", label: "Home", icon: ICONS.home },
  { id: "today", label: "Today", icon: ICONS.today },
  { id: "tasks", label: "Tasks", icon: ICONS.tasks },
  { id: "calendar", label: "Calendar", icon: ICONS.calendar },
  { id: "trackers", label: "Trackers", icon: ICONS.trackers },
  { id: "learning", label: "Learning", icon: ICONS.learning },
  { id: "books", label: "Books", icon: ICONS.books },
  { id: "projects", label: "Projects", icon: ICONS.projects }
];
var HEADER = {
  home: { eyebrow: "Good evening,", name: "Candice" },
  today: { eyebrow: "Today", name: "Candice" },
  tasks: { eyebrow: "Your tasks", name: "Candice" },
  calendar: { eyebrow: "Good evening,", name: "Candice" },
  trackers: { eyebrow: "Health & habits", name: "Trackers" },
  learning: { eyebrow: "Your library", name: "Learning" },
  books: { eyebrow: "Your shelf", name: "Books" },
  projects: { eyebrow: "In progress", name: "Projects" }
};
function bloomMark() {
  return `<svg class="bloom-mark" viewBox="0 0 32 32" role="img" aria-label="Bloom">
    <defs><linearGradient id="bm-bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#f2a0b5"/><stop offset="1" stop-color="#e8935f"/>
    </linearGradient></defs>
    <rect width="32" height="32" rx="9" fill="url(#bm-bg)"/>
    <g fill="#ffffff">
      <circle cx="16" cy="8.5" r="3.1"/><circle cx="23.5" cy="16" r="3.1"/>
      <circle cx="16" cy="23.5" r="3.1"/><circle cx="8.5" cy="16" r="3.1"/>
    </g>
    <circle cx="16" cy="16" r="3.6" fill="#d9a441"/>
  </svg>`;
}
function taskCard(t) {
  const bar = t.progress != null ? `<div class="t-bar"><div class="t-bar-fill" style="width:${t.progress}%"></div></div>
         <div class="t-prog">${t.progress}%</div>` : "";
  return `<div class="t-card">
    <span class="t-tag" style="color:${t.color}">${t.category}</span>
    <div class="t-name">${t.name}</div>
    ${bar}
  </div>`;
}
var BOARD_COLS = [
  { key: "todo", title: "To Do", dot: "var(--c-pink)", tint: "#faf2ef", countBg: "#fdeef2", countFg: "#b5627c" },
  { key: "doing", title: "In Progress", dot: "var(--c-peach)", tint: "#fdf2e8", countBg: "#fdf2e8", countFg: "#c07a3f" },
  { key: "done", title: "Done", dot: "var(--c-sage)", tint: "#f0f7ee", countBg: "#eaf4ea", countFg: "#4f7a3a" }
];
function tasksView(d) {
  const open = d.tasks.todo.length + d.tasks.doing.length;
  const cols = BOARD_COLS.map((c) => {
    const list = d.tasks[c.key].map(taskCard).join("");
    const count = d.tasks[c.key].length;
    return `<div class="board-col" style="--tint:${c.tint}">
      <div class="board-col-head">
        <span class="col-dot" style="background:${c.dot}"></span>
        <span class="col-title">${c.title}</span>
        <span class="col-count" style="background:${c.countBg};color:${c.countFg}">${count}</span>
      </div>
      <div class="board-col-body">${list}</div>
    </div>`;
  }).join("");
  return `<section class="view hidden" data-view="tasks">
    <div class="board-head">
      <div><div class="board-title">Task Board</div>
        <div class="board-sub">${open} open \xB7 ${d.tasks.done.length} done today</div></div>
      <button class="btn-primary" id="new-task-btn">+ New task</button>
    </div>
    <div class="board">${cols}</div>
  </section>`;
}
function homeView(d) {
  const stat = d.statStrip.map(
    (s) => {
      var _a;
      return `<div class="stat">
        <div class="s-label">${s.label}</div>
        <div class="s-value">${s.value}${s.unit ? `<span class="s-unit">${s.unit}</span>` : ""}</div>
        <div class="s-sub">${(_a = s.sub) != null ? _a : ""}</div>
      </div>`;
    }
  ).join("");
  const todayRows = d.todayTasks.map(
    (t) => `<div class="chk-row ${t.done ? "done" : ""}">
        <span class="chk ${t.done ? "on" : ""}">${t.done ? "\u2713" : ""}</span>
        <span class="chk-name">${t.name}</span>
      </div>`
  ).join("");
  const projRows = d.projects.map(
    (p) => `<div class="proj">
        <div class="proj-top"><span class="proj-name">${p.name}</span><span class="proj-pct">${p.progress}%</span></div>
        <div class="proj-bar"><div class="proj-fill" style="width:${p.progress}%"></div></div>
      </div>`
  ).join("");
  const flowTiles = d.dailyFlow.map((f) => `<div class="flow-tile"><div class="flow-ico">${f.icon}</div><div class="flow-label">${f.label}</div></div>`).join("");
  const expCats = d.expenses.categories.map((c) => `<div class="exp-seg" style="width:${c.pct}%;background:${c.color}"></div>`).join("");
  const expList = d.expenses.categories.map(
    (c) => `<div class="exp-row"><span class="swatch" style="background:${c.color}"></span>
        <span class="exp-name">${c.name}</span><span class="exp-amt">\xA5${c.amount.toFixed(2)}</span></div>`
  ).join("");
  const wellItems = d.wellness.map(
    (w) => {
      var _a;
      return `<div class="well-item">
        <div class="well-label" style="color:${(_a = w.color) != null ? _a : "var(--ink)"}">${w.label}</div>
        <div class="well-value">${w.value}</div>
        <div class="well-sub">${w.sub}</div>
      </div>`;
    }
  ).join("");
  return `<section class="view" data-view="home">
    <div class="stat-strip">${stat}</div>
    <div class="dash-grid">
      <div class="dash-left">
        <div class="card">
          <div class="card-head">
            <div><div class="t-title">Today's Tasks</div></div>
            <span class="pill">${d.todayTasks.filter((t) => t.done).length}/${d.todayTasks.length}</span>
          </div>
          <div class="chk-list">${todayRows}</div>
        </div>
        <div class="card">
          <div class="card-head">
            <div><div class="t-title">Active Projects</div></div>
            <a class="link" href="#">View all</a>
          </div>
          <div class="proj-list">${projRows}</div>
        </div>
      </div>
      <div class="dash-right">
        <div class="card">
          <div class="card-head"><div><div class="t-title accent-peach">Daily Flow</div></div></div>
          <div class="flow">${flowTiles}</div>
        </div>
        <div class="card">
          <div class="card-head">
            <div><div class="t-title">Expenses</div></div>
            <span class="tag-mini">${d.expenses.monthTag}</span>
          </div>
          <div class="exp-today">\xA5${d.expenses.today.toFixed(2)} <span>today</span></div>
          <div class="exp-bar">${expCats}</div>
          <div class="exp-list">${expList}</div>
        </div>
        <div class="card">
          <div class="card-head"><div><div class="t-title">Wellness</div></div></div>
          <div class="well">${wellItems}</div>
        </div>
        <div class="card lib-card">
          <div class="lib-item"><span class="lib-num">${d.library.subjects}</span><span class="lib-lbl">subjects</span><span class="lib-cap">Learning</span></div>
          <div class="lib-item"><span class="lib-num">${d.library.books}</span><span class="lib-lbl">read</span><span class="lib-cap">Books</span></div>
        </div>
      </div>
    </div>
  </section>`;
}
function calendarView(d) {
  const c = d.calendar;
  const lead = (c.firstDayJS + 6) % 7;
  const dow = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
  let cells = "";
  for (let i = 0; i < lead; i++)
    cells += `<div class="cal-cell empty"></div>`;
  for (let day = 1; day <= c.daysInMonth; day++) {
    const isToday = day === c.today;
    const ev = c.events.find((e) => e.day === day);
    const cls = ["cal-cell", isToday ? "today" : "", ev ? "event " + ev.kind : ""].filter(Boolean).join(" ");
    cells += `<div class="${cls}">
      <span class="cal-day">${day}</span>
      ${isToday ? '<span class="cal-today">Today</span>' : ""}
    </div>`;
  }
  const imp = d.importantDates.map(
    (e) => `<div class="imp-item">
        <span class="imp-pill" style="background:${e.color}1f;color:${e.color}">${e.date}</span>
        <span class="imp-title">${e.title}</span>
      </div>`
  ).join("");
  const noteLines = d.todayNote.lines.map((l) => `<div class="tn-line">${l}</div>`).join("");
  return `<section class="view hidden" data-view="calendar">
    <div class="cal-wrap">
      <div class="cal-main card">
        <div class="cal-top">
          <div class="cal-title">${c.monthLabel}</div>
          <div class="cal-nav">
            <button class="cal-arrow" aria-label="Previous month">${ICONS.chevL}</button>
            <button class="cal-arrow" aria-label="Next month">${ICONS.chevR}</button>
          </div>
        </div>
        <div class="cal-grid">
          ${dow.map((x) => `<div class="cal-dow">${x}</div>`).join("")}
          ${cells}
        </div>
      </div>
      <div class="cal-side">
        <div class="card">
          <div class="card-head"><div><div class="t-title">Important Dates</div></div></div>
          <div class="imp-list">${imp}</div>
        </div>
        <div class="card">
          <div class="card-head"><div><div class="t-title">${d.todayNote.title}</div></div></div>
          <div class="tn">${noteLines}</div>
        </div>
      </div>
    </div>
  </section>`;
}
function weightChart(d) {
  const w = d.trackers.weight;
  const pts = w.points;
  if (pts.length === 1) {
    return `<svg class="chart" viewBox="0 0 464 150" preserveAspectRatio="none" role="img" aria-label="Weight trend">
      <line class="grid-line" x1="34" y1="35" x2="448" y2="35"/>
      <line class="grid-line" x1="34" y1="80" x2="448" y2="80"/>
      <line class="grid-line" x1="34" y1="125" x2="448" y2="125"/>
      <line class="axis" x1="34" y1="140" x2="448" y2="140"/>
      <circle class="pt" cx="232" cy="80" r="6"/>
      <text class="pt-label" x="232" y="62" text-anchor="middle">${pts[0].toFixed(1)}</text>
      <text class="axis-label" x="232" y="150" text-anchor="middle">${w.labels[0]}</text>
    </svg>`;
  }
  return `<svg class="chart" viewBox="0 0 464 150" preserveAspectRatio="none"><line class="axis" x1="34" y1="140" x2="448" y2="140"/></svg>`;
}
function donut(cats, total, month) {
  const seg = cats.map((c) => `<div class="legend-row"><span class="swatch" style="background:${c.color}"></span>${c.name} \xB7 \xA5${c.amount.toFixed(2)} \xB7 ${c.pct}%</div>`).join("");
  return `<div class="chart-row">
    <div class="donut"><div class="donut-center"><b>\xA5${total.toFixed(0)}</b><span>${month.split(" ")[0]}</span></div></div>
    <div class="legend">${seg}</div>
  </div>`;
}
function trackersView(d) {
  const w = d.trackers.weight;
  const p = d.trackers.period;
  const e = d.trackers.expense;
  const cyclePct = (p.dayOfCycle / p.cycleDays * 100).toFixed(1);
  const ms = d.trackers.month;
  return `<section class="view hidden" data-view="trackers">
    <div class="dash-grid">
      <div class="dash-left">
        <div class="card">
          <div class="card-head">
            <div><div class="t-title">Weight Trend</div><div class="t-sub">${w.unit} \xB7 logged daily</div></div>
            <div class="t-value">${w.current.toFixed(1)}</div>
          </div>
          ${weightChart(d)}
          <div class="note">Start ${w.start.toFixed(1)} \xB7 Current ${w.current.toFixed(1)} \xB7 Change ${w.change >= 0 ? "+" : ""}${w.change.toFixed(1)} ${w.unit}</div>
        </div>
        <div class="card">
          <div class="card-head">
            <div><div class="t-title">Expense Overview</div><div class="t-sub">${e.month}</div></div>
            <div class="t-value small">\xA5${e.total.toFixed(2)}</div>
          </div>
          ${donut(e.categories, e.total, e.month)}
        </div>
      </div>
      <div class="dash-right">
        <div class="card">
          <div class="card-head"><div><div class="t-title">Cycle Tracker</div><div class="t-sub">Day ${p.dayOfCycle} of ${p.cycleDays}</div></div></div>
          <div class="ring-wrap">
            <div class="cycle-ring" style="--p:${cyclePct}%"><div class="cr-center"><b>Day ${p.dayOfCycle}</b><span>of ${p.cycleDays}</span></div></div>
            <div class="cycle-info">
              <div class="ci-row"><span>Last period</span><b>${p.last}</b></div>
              <div class="ci-row"><span>Next predicted</span><b>${p.next}</b></div>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-head"><div><div class="t-title">This Month</div><div class="t-sub">${e.month}</div></div></div>
          <div class="month-stats">
            <div class="month-stat"><b>${ms.weight}</b><span>Weight (kg)</span></div>
            <div class="month-stat"><b>${ms.expense}</b><span>Expenses</span></div>
            <div class="month-stat"><b>${ms.cycle}</b><span>Cycle</span></div>
          </div>
        </div>
      </div>
    </div>
  </section>`;
}
function placeholderView(id, title) {
  return `<section class="view hidden" data-view="${id}">
    <div class="card placeholder">
      <div class="ph-emoji">\u{1F331}</div>
      <div class="ph-title">${title}</div>
      <div class="ph-sub">Part of the Bloom design \u2014 wiring this section to your vault is the next step.</div>
    </div>
  </section>`;
}
function buildShell(d, _now, initialView = "home") {
  var _a;
  const navItems = NAV.map(
    (n) => `<button class="nav-item ${n.id === initialView ? "active" : ""}" data-nav="${n.id}">${n.icon}<span>${n.label}</span></button>`
  ).join("");
  const h = (_a = HEADER[initialView]) != null ? _a : HEADER.home;
  return `<div class="bloom" id="bloom-root">
    <aside class="bloom-sidebar">
      <div class="brand">${bloomMark()}<div class="brand-text"><b>Bloom</b><span>${d.logoSub}</span></div></div>
      <div class="nav-label">MENU</div>
      <nav class="nav">${navItems}</nav>
      <div class="sidebar-footer">
        <div class="profile">
          <div class="avatar">${d.owner.charAt(0)}</div>
          <div class="who"><b>${d.owner}</b><span>${d.planLabel}</span></div>
        </div>
      </div>
    </aside>
    <main class="bloom-main">
      <header class="bloom-header">
        <div class="hdr-greet">
          <div class="hdr-eyebrow" id="hdr-eyebrow">${h.eyebrow}</div>
          <div class="hdr-name" id="hdr-name">${h.name}</div>
          <div class="hdr-date" id="hdr-date">${d.dateLabel}</div>
        </div>
        <div class="header-right">
          <div class="search-box">${ICONS.search}<input id="bloom-search" type="text" placeholder="Search tasks, notes\u2026" /></div>
          <button class="theme-toggle" id="theme-toggle" title="Toggle light / dark" aria-label="Toggle theme">
            <span class="sun">${ICONS.sun}</span><span class="moon">${ICONS.moon}</span><span class="knob"></span>
          </button>
          <button class="icon-btn" id="settings-btn" title="Settings">${ICONS.settings}</button>
        </div>
      </header>
      <div class="bloom-scroll"><div class="bloom-content">
        ${homeView(d)}
        ${tasksView(d)}
        ${calendarView(d)}
        ${trackersView(d)}
        ${placeholderView("today", "Today")}
        ${placeholderView("learning", "Learning")}
        ${placeholderView("books", "Books")}
        ${placeholderView("projects", "Projects")}
      </div></div>
    </main>
  </div>`;
}
function showView(root, id) {
  var _a;
  root.querySelectorAll(".view").forEach((v) => {
    v.classList.toggle("hidden", v.dataset.view !== id);
  });
  root.querySelectorAll(".nav-item").forEach((n) => {
    n.classList.toggle("active", n.dataset.nav === id);
  });
  const h = (_a = HEADER[id]) != null ? _a : HEADER.home;
  const eyebrow = root.querySelector("#hdr-eyebrow");
  const name = root.querySelector("#hdr-name");
  if (eyebrow)
    eyebrow.textContent = h.eyebrow;
  if (name)
    name.textContent = h.name;
}

// src/data.ts
function loadBloomData2() {
  return {
    owner: "Candice",
    logoSub: "vault OS",
    planLabel: "Free plan",
    dateLabel: "Sunday, August 16",
    statStrip: [
      { label: "Tasks", value: "2/5", sub: "done today" },
      { label: "Weight", value: "50.0", unit: "kg", sub: "0.0 this week" },
      { label: "Cycle", value: "Day 4", sub: "/ 28" },
      { label: "Reading", value: "12", sub: "books read" }
    ],
    todayTasks: [
      { name: "Cook dinner", done: false },
      { name: "Clean litter box", done: true },
      { name: "Water plants", done: false },
      { name: "Skincare routine", done: true },
      { name: "Take out trash", done: false }
    ],
    projects: [
      { name: "Redesign portfolio", progress: 60 },
      { name: "Learn Python", progress: 35 }
    ],
    dailyFlow: [
      { label: "Today", icon: "\u2600" },
      { label: "Tasks", icon: "\u2713" },
      { label: "Learn", icon: "\u{1F4DA}" },
      { label: "Capture", icon: "\u270E" },
      { label: "Review", icon: "\u21BA" }
    ],
    expenses: {
      today: 45,
      monthTag: "AUG",
      categories: [{ name: "Other", amount: 45, pct: 100, color: "var(--accent)" }]
    },
    wellness: [
      { label: "Weight", value: "50.0 kg", sub: "0.0 this week", color: "var(--c-sage)" },
      { label: "Cycle", value: "Day 4", sub: "Next \xB7 Sep 10", color: "var(--c-peri)" }
    ],
    library: { subjects: 5, books: 12 },
    tasks: {
      todo: [
        { name: "Cook dinner", category: "Daily", color: "#b5627c" },
        { name: "Water plants", category: "Daily", color: "#b5627c" },
        { name: "Take out trash", category: "Daily", color: "#b5627c" },
        { name: "Study economics", category: "Learning", color: "#4f7a3a" },
        { name: "Practice AI coding", category: "Learning", color: "#4f7a3a" }
      ],
      doing: [
        { name: "Clean litter box", category: "Daily", color: "#b5627c" },
        { name: "Skincare routine", category: "Daily", color: "#b5627c" },
        { name: "Redesign portfolio", category: "Project", color: "#5a6aa0", progress: 60 },
        { name: "Learn Python", category: "Learning", color: "#4f7a3a", progress: 35 }
      ],
      done: [
        { name: "Set up vault", category: "Daily", color: "#b5627c" },
        { name: "Task 4", category: "Project", color: "#5a6aa0" },
        { name: "Skincare science", category: "Learning", color: "#4f7a3a" }
      ]
    },
    calendar: {
      monthLabel: "August 2026",
      year: 2026,
      monthIndex: 7,
      firstDayJS: 6,
      // Aug 1, 2026 is a Saturday
      daysInMonth: 31,
      today: 16,
      events: [
        { day: 20, kind: "peach" },
        { day: 25, kind: "peri" }
      ]
    },
    importantDates: [
      { date: "Aug 20", title: "Dentist appointment", color: "#e8935f" },
      { date: "Aug 25", title: "Project deadline", color: "#7d8cc4" }
    ],
    todayNote: {
      title: "Daily Note \xB7 Aug 16",
      lines: ["Weight 50 kg \xB7 Mood: good", "Study 25 min \u2014 economics", "Expenses: \xA545"]
    },
    trackers: {
      weight: {
        current: 50,
        start: 50,
        change: 0,
        unit: "kg",
        points: [50],
        labels: ["Aug 16"]
      },
      expense: {
        total: 45,
        month: "August 2026",
        categories: [{ name: "Other", amount: 45, pct: 100, color: "var(--accent)" }]
      },
      period: { dayOfCycle: 4, cycleDays: 28, last: "2026-08-13", next: "2026-09-10" },
      month: { weight: "50.0", expense: "\xA545", cycle: "Day 4" }
    }
  };
}

// src/vault.ts
var MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December"
];
var EXPENSE_COLORS = {
  Food: "#d9a340",
  Shopping: "#e8935f",
  Transport: "#5ca3a1",
  Pet: "#7fb069",
  Home: "#7d8cc4",
  Health: "#e07a9c",
  Beauty: "#c77baf",
  Other: "var(--accent)"
};
function stripCode(md) {
  return md.replace(/```[\s\S]*?```/g, "");
}
function readTable(block) {
  const rows = [];
  for (const line of block.split("\n")) {
    const t = line.trim();
    if (!t.startsWith("|"))
      continue;
    if (/^\|[\s:-]+\|$/.test(t))
      continue;
    rows.push(t.split("|").slice(1, -1).map((c) => c.trim()));
  }
  return rows;
}
function tablesAfter(md, header) {
  const i = md.indexOf(header);
  if (i < 0)
    return [];
  const rest = md.slice(i);
  const end = rest.search(/\n##\s/);
  const block = end > 0 ? rest.slice(0, end) : rest;
  return readTable(block);
}
function fmtISO(d) {
  const p = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}
function fmtShort(iso) {
  const m = iso.match(/(\d{4})-(\d{2})-(\d{2})/);
  if (!m)
    return iso;
  return `${MONTHS[parseInt(m[2], 10) - 1].slice(0, 3)} ${parseInt(m[3], 10)}`;
}
function catColor(c) {
  return c === "Daily" ? "#b5627c" : c === "Learning" ? "#4f7a3a" : "#5a6aa0";
}
function collectTasks(md, category) {
  const out = [];
  if (!md)
    return out;
  for (const line of stripCode(md).split("\n")) {
    const m = line.match(/^\s*-\s*\[([ xX])\]\s*(.*)$/);
    if (!m)
      continue;
    const raw = m[2];
    if (!raw.trim())
      continue;
    if (/\(example\)|（模拟任务）|\(模擬任務\)/.test(raw))
      continue;
    const name = raw.replace(/\s*→\s*\[\[[^\]]*\]\]/g, "").replace(/\s*\*\s*\(.*?\)\s*/g, "").replace(/[*(]/g, "").trim();
    if (!name)
      continue;
    out.push({ name, done: m[1].toLowerCase() === "x", category });
  }
  return out;
}
function parseProjects(md) {
  const out = [];
  const clean = stripCode(md);
  const i = clean.indexOf("## Active Projects");
  if (i < 0)
    return out;
  const rest = clean.slice(i);
  const end = rest.search(/\n##\s/);
  const block = end > 0 ? rest.slice(0, end) : rest;
  const lines = block.split("\n");
  for (let k = 0; k < lines.length; k++) {
    const h = lines[k].match(/^###\s+\d+\.\s+(.*)$/);
    if (!h)
      continue;
    const name = h[1].trim();
    if (!name || /name here|second project/i.test(name))
      continue;
    let progress = 0;
    for (let j = 1; j <= 4 && k + j < lines.length; j++) {
      const pm = lines[k + j].match(/<progress\s+value="(\d+)"/);
      if (pm) {
        progress = parseInt(pm[1], 10);
        break;
      }
    }
    out.push({ name, progress });
  }
  return out;
}
async function loadBloomDataLive(app) {
  var _a;
  const d = loadBloomData2();
  const now = /* @__PURE__ */ new Date();
  const read = async (p) => {
    try {
      return await app.vault.adapter.read(p);
    } catch (e) {
      return null;
    }
  };
  const wt = await read("13-Trackers/Weight Tracker.md");
  if (wt) {
    const rows = tablesAfter(wt, "## Daily Weight Log").filter((r) => r[0] && r[1] && !isNaN(parseFloat(r[1]))).map((r) => ({ date: r[0], w: parseFloat(r[1]) }));
    if (rows.length) {
      const current = rows[rows.length - 1].w;
      const start = rows[0].w;
      const change = +(current - start).toFixed(1);
      d.trackers.weight = { current, start, change, unit: "kg", points: rows.map((r) => r.w), labels: rows.map((r) => r.date) };
      d.statStrip[1] = { label: "Weight", value: current.toFixed(1), unit: "kg", sub: `${change >= 0 ? "+" : ""}${change} this week` };
      d.wellness[0] = { label: "Weight", value: `${current.toFixed(1)} kg`, sub: `${change >= 0 ? "+" : ""}${change} this week`, color: "var(--c-sage)" };
      d.trackers.month.weight = current.toFixed(1);
    }
  }
  const pt = await read("13-Trackers/Period Tracker.md");
  if (pt) {
    const rows = tablesAfter(pt, "## Current Cycle");
    const get = (k) => {
      var _a2, _b, _c;
      return (_c = (_b = (_a2 = rows.find((r) => r[0].includes(k))) == null ? void 0 : _a2[1]) == null ? void 0 : _b.trim()) != null ? _c : "";
    };
    const last = get("Last period");
    const cycleDays = parseInt(get("Cycle length"), 10) || 28;
    const next = get("Predicted next");
    const dayOfCycle = parseInt(get("Today is day"), 10) || 1;
    d.trackers.period = { dayOfCycle, cycleDays, last, next };
    d.statStrip[2] = { label: "Cycle", value: `Day ${dayOfCycle}`, sub: `/ ${cycleDays}` };
    d.wellness[1] = { label: "Cycle", value: `Day ${dayOfCycle}`, sub: `Next \xB7 ${fmtShort(next)}`, color: "var(--c-peri)" };
    d.trackers.month.cycle = `Day ${dayOfCycle}`;
  }
  const ex = await read("13-Trackers/Expense Tracker.md");
  if (ex) {
    const rows = tablesAfter(ex, "## Daily Expense Log").filter((r) => r[0] && !isNaN(parseFloat(r[3]))).map((r) => ({ date: r[0], cat: r[1] || "Other", amt: parseFloat(r[3]) }));
    if (rows.length) {
      const sums = /* @__PURE__ */ new Map();
      rows.forEach((r) => {
        var _a2;
        return sums.set(r.cat, ((_a2 = sums.get(r.cat)) != null ? _a2 : 0) + r.amt);
      });
      const total = [...sums.values()].reduce((a, b) => a + b, 0);
      const categories = [...sums.entries()].map(([name, amount]) => {
        var _a2;
        return {
          name,
          amount: +amount.toFixed(2),
          pct: Math.round(amount / total * 100) || 0,
          color: (_a2 = EXPENSE_COLORS[name]) != null ? _a2 : "var(--accent)"
        };
      });
      const todayAmt = rows.filter((r) => r.date === fmtISO(now)).reduce((a, b) => a + b.amt, 0);
      const monthLabel = `${MONTHS[now.getMonth()]} ${now.getFullYear()}`;
      d.expenses = { today: +todayAmt.toFixed(2), monthTag: MONTHS[now.getMonth()].slice(0, 3).toUpperCase(), categories };
      d.trackers.expense = { total: +total.toFixed(2), month: monthLabel, categories };
      d.trackers.month.expense = `\xA5${total.toFixed(0)}`;
    }
  }
  const rawDaily = collectTasks(await read("11-Todo/Daily Tasks.md"), "Daily");
  const rawStudy = collectTasks(await read("11-Todo/Study Tasks.md"), "Learning");
  const rawProj = collectTasks(await read("11-Todo/Project Tasks.md"), "Project");
  const todayTasks = rawDaily.slice(0, 6).map((t) => ({ name: t.name, done: t.done }));
  if (todayTasks.length) {
    const done = todayTasks.filter((t) => t.done).length;
    d.todayTasks = todayTasks;
    d.statStrip[0] = { label: "Tasks", value: `${done}/${todayTasks.length}`, sub: "done today" };
  }
  const all = [...rawDaily, ...rawStudy, ...rawProj];
  const toTask = (t) => ({ name: t.name, category: t.category, color: catColor(t.category) });
  d.tasks = {
    todo: all.filter((t) => !t.done).map(toTask),
    done: all.filter((t) => t.done).map(toTask),
    doing: d.tasks.doing
    // filled below from projects
  };
  const pd = await read("10-Projects/Project Dashboard.md");
  if (pd) {
    const projs = parseProjects(pd);
    if (projs.length) {
      d.projects = projs.map((p) => ({ name: p.name, progress: p.progress }));
      d.tasks.doing = projs.map((p) => ({
        name: p.name,
        category: "Project",
        color: "#5a6aa0",
        progress: p.progress
      }));
    }
  }
  const year = now.getFullYear();
  const monthIndex = now.getMonth();
  d.calendar = {
    monthLabel: `${MONTHS[monthIndex]} ${year}`,
    year,
    monthIndex,
    firstDayJS: new Date(year, monthIndex, 1).getDay(),
    daysInMonth: new Date(year, monthIndex + 1, 0).getDate(),
    today: now.getDate(),
    events: d.calendar.events
  };
  const cal = await read("12-Calendar/Monthly Calendar.md");
  if (cal) {
    const rows = tablesAfter(cal, "## Important Dates");
    const events = [];
    const imp = [];
    const palette = ["#e8935f", "#7d8cc4", "#7fb069", "#e07a9c"];
    rows.forEach((r) => {
      var _a2, _b;
      const dateStr = r[0] || "";
      const title = (_b = (_a2 = r[1]) == null ? void 0 : _a2.replace(/\*.*?\*|\(.*?\)/g, "").trim()) != null ? _b : "";
      if (!dateStr || !title || /example/i.test(title))
        return;
      const dm = dateStr.match(/(\d{4})-(\d{2})-(\d{2})/);
      if (!dm)
        return;
      const day = parseInt(dm[3], 10);
      events.push({ day, kind: /doctor|appointment|预约|医生/.test(title) ? "peri" : "peach" });
      imp.push({ date: fmtShort(dateStr), title, color: palette[imp.length % palette.length] });
    });
    if (events.length)
      d.calendar.events = events;
    if (imp.length)
      d.importantDates = imp;
  }
  const dn = await read(`12-Calendar/Daily Notes/${fmtISO(now)}.md`);
  if (dn) {
    const lines = [];
    const wM = (_a = dn.match(/weight:\s*"(\d+(?:\.\d+)?)"/i)) != null ? _a : dn.match(/\|\s*Weight \(kg\)\s*\|\s*(\d+(?:\.\d+)?)\s*\|/);
    const weight = wM ? parseFloat(wM[1]) : NaN;
    const moodM = dn.match(/\|\s*Mood\s*\|\s*([^|]+)\|/);
    let mood = "";
    if (moodM) {
      const m = moodM[1];
      if (/😊|🙂|good|happy|good/i.test(m))
        mood = "good";
      else if (/😔|😟|sad|low/i.test(m))
        mood = "low";
    }
    if (!isNaN(weight))
      lines.push(`Weight ${weight} kg${mood ? " \xB7 Mood: " + mood : ""}`);
    const totalM = dn.match(/\|\s*\*\*Total\*\*\s*\|[^|]*\|\s*\*\*(\d+(?:\.\d+)?)\*\*/);
    if (totalM)
      lines.push(`Expenses: \xA5${totalM[1]}`);
    if (lines.length)
      d.todayNote = { title: `Daily Note \xB7 ${fmtShort(fmtISO(now))}`, lines };
  }
  const learn = await read("14-Learning/README.md");
  if (learn) {
    const subj = tablesAfter(learn, "## Subjects").filter((r) => r[0] && !/^Subject/i.test(r[0])).length;
    if (subj > 0)
      d.library = { subjects: subj, books: d.library.books };
  }
  const books = await read("15-Books/Book List.md");
  if (books) {
    const count = readTable(stripCode(books)).filter(
      (r) => r[0] && !/^(Title|Category|Book|Subject|Author)/i.test(r[0])
    ).length;
    if (count > 0)
      d.library.books = count;
  }
  return d;
}

// src/main.ts
var VIEW_TYPE_BLOOM = "bloom-view";
var DEFAULT_SETTINGS = { dark: false };
var BloomView = class extends import_obsidian.ItemView {
  constructor(leaf, settings) {
    super(leaf);
    __publicField(this, "currentView", "home");
    __publicField(this, "dark", false);
    __publicField(this, "settings");
    // back-reference set by the plugin
    __publicField(this, "plugin");
    this.settings = settings;
    this.dark = settings.dark;
  }
  getViewType() {
    return VIEW_TYPE_BLOOM;
  }
  getDisplayText() {
    return "Bloom";
  }
  getIcon() {
    return "layout-dashboard";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
    this.containerEl.empty();
  }
  setExternalView(id) {
    this.currentView = id;
    this.showView(id);
  }
  setExternalTheme(dark) {
    this.dark = dark;
    this.settings.dark = dark;
    this.applyTheme();
  }
  async render() {
    this.containerEl.empty();
    const wrap = this.containerEl.createDiv();
    try {
      const data = await loadBloomDataLive(this.app).catch((e) => {
        console.error("[Bloom] live data failed, using static fallback:", e);
        return loadBloomData();
      });
      wrap.innerHTML = buildShell(data, /* @__PURE__ */ new Date(), this.currentView);
      this.wire(wrap);
      this.applyTheme();
    } catch (e) {
      console.error("[Bloom] render failed:", e);
      wrap.innerHTML = '<div style="padding:24px;color:#b5627c">Bloom failed to render \u2014 see DevTools console.</div>';
    }
  }
  applyTheme() {
    const root = this.containerEl.querySelector(".bloom");
    if (root)
      root.toggleClass("theme-dark", this.dark);
  }
  showView(id) {
    showView(this.containerEl, id);
  }
  wire(root) {
    root.querySelectorAll(".nav-item").forEach((btn) => {
      btn.addEventListener("click", () => {
        const id = btn.dataset.nav;
        this.currentView = id;
        this.showView(id);
      });
    });
    root.querySelectorAll(".search-box input").forEach((inp) => {
      inp.addEventListener("input", () => this.filterTasks(inp.value.trim().toLowerCase()));
    });
    const toggle = root.querySelector("#theme-toggle");
    toggle == null ? void 0 : toggle.addEventListener("click", () => {
      this.dark = !this.dark;
      this.settings.dark = this.dark;
      this.plugin.saveSettings();
      this.applyTheme();
    });
  }
  filterTasks(q) {
    const tasksView2 = this.containerEl.querySelector('.view[data-view="tasks"]');
    if (!tasksView2)
      return;
    tasksView2.querySelectorAll(".t-card").forEach((card) => {
      var _a, _b, _c;
      const name = (_c = (_b = (_a = card.querySelector(".t-name")) == null ? void 0 : _a.textContent) == null ? void 0 : _b.toLowerCase()) != null ? _c : "";
      card.style.display = !q || name.includes(q) ? "" : "none";
    });
  }
};
var BloomPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings", DEFAULT_SETTINGS);
    __publicField(this, "view", null);
  }
  async onload() {
    try {
      console.log("[Bloom] onload start");
      await this.loadSettings();
      this.registerView(VIEW_TYPE_BLOOM, (leaf) => {
        const v = new BloomView(leaf, this.settings);
        v.plugin = this;
        this.view = v;
        return v;
      });
      this.addRibbonIcon("layout-dashboard", "Open Bloom", () => this.activateView());
      this.addCommand({
        id: "open-bloom",
        name: "Open Bloom dashboard",
        callback: () => this.activateView()
      });
      this.addCommand({
        id: "toggle-bloom-theme",
        name: "Toggle light / dark theme",
        callback: () => {
          var _a;
          const next = !this.settings.dark;
          this.settings.dark = next;
          (_a = this.view) == null ? void 0 : _a.setExternalTheme(next);
          this.saveSettings();
        }
      });
      new import_obsidian.Notice("Bloom dashboard ready \u2014 click the dashboard icon in the left ribbon.");
      console.log("[Bloom] onload complete");
    } catch (e) {
      console.error("[Bloom] onload failed:", e);
      new import_obsidian.Notice("Bloom failed to load: " + (e instanceof Error ? e.message : String(e)));
    }
  }
  async activateView() {
    var _a;
    const { workspace } = this.app;
    let leaf = null;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_BLOOM);
    if (existing.length) {
      leaf = existing[0];
    } else {
      leaf = (_a = workspace.getRightLeaf(false)) != null ? _a : workspace.getLeaf(true);
      await leaf.setViewState({ type: VIEW_TYPE_BLOOM, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
